apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  #namespace: fullstack
  namespace: three-tier
  labels:
    role: frontend
spec: 
  replicas: 1
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: persevcareers6577/perseverance-project:${env.version}
        ports:
        - containerPort: 3000
